# Exported from:        http://DAI-100SQ04:5516/
# Release version:      25.1.4-808.849
# Date created:         Fri Jan 23 15:47:58 IST 2026

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Template_first.yaml
  - Variables.yaml
  - Template_second.yaml
  - Template_IR_DLR_Group_Releases.yaml
  - Template_Deploy + SE - Optional.yaml
