# Exported from:        http://DAI-100SQ04:5516/
# Release version:      25.1.4-808.849
# Date created:         Fri Jan 23 15:47:58 IST 2026

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: gitops-cynthia
spec:
- template: first
  scheduledStartDate: 2026-01-23T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: New task
      type: xlrelease.Task
  riskProfile: Default risk profile
  author: admin
